### PR TITLE
Peloton To Garmin Version 2 - Fit files

### PR DESCRIPTION
**Pull request by philosowaffle**
This is stable enough to be a beta release at this point.  You can test it out by using this [Docker Compose File](https://github.com/philosowaffle/peloton-to-garmin/blob/fitFiles/docker-compose-fit.yaml).  Sample [configuration.local.json](https://github.com/philosowaffle/peloton-to-garmin/blob/fitFiles/PelotonToFit/configuration.example.json).

---

Garmin provides an SDK for writing FIT files: https://developer.garmin.com/fit/overview/

C# SDK is provided, and the code will be just complex enough that I will happily switch back to my native programming language. Python is great and all, but not my most fluent language.

With .net core, should be able to maintain cross platform compatibility in the event I can figure out the FIT protocol.

Pros of FIT:
- Supports way more data than TCX
- I get to switch to C# and stop writing python :D

Cons of FIT:
- Complex protocol
- No python library I could find for writing files
- Will need to rewrite most of the existing code in C#

---
Some notes on why I'm continuing down the c# path and not working with one of the python libraries:

1. https://github.com/jaroslawhartman/withings-sync - Looks great, but I'd need to copy some of their code into this code base and I don't actually understand what the code is doing which means I would not be able to enhance or modify it going forward.
2. https://github.com/dtcooper/python-fitparse - Only supports parsing fit files, not writing them. There is a branch where someone has added writing support but same as point 1, I don't understand it well enough to pull into this project and support long term.
3. The FIT protocol is very complex and the C# library I'm using is easy to use and officially published by Garmin itself.
4. In the age of .netcore, this project should continue to run on multiple OS's.
5. My day job is C#, I only dabble in python on the weekends.

### CODE REVIEW

**Comment by danielsfrazier** [comment]
Have a look at this project. They are pulling data from withings and uploading to garmin using fit file format and python. I dont have peleton yet, was just seeing what was out there to sync with garmin in the future.

https://github.com/jaroslawhartman/withings-sync

**Comment by philosowaffle** [comment]
Thanks! I'm going to have to take a look at this.

**Comment by grizzls** [comment]
Would this be useful? https://github.com/dtcooper/python-fitparse

**Comment by philosowaffle** [comment]
I think I've got all the core metrics coming in via FIT file now. Still have not figured out how to set custom Power zones, HR zones, or a target range on the graph.  Seem to have all the info we need from the peloton api, just have to figure out how to correctly set it in the fit file.

**Comment by philosowaffle** [comment]
https://github.com/philosowaffle/peloton-to-garmin/projects/1

**Comment by philosowaffle** [comment]
Some notes on why I'm continuing down the c# path and not working with one of the python libraries:

1. https://github.com/jaroslawhartman/withings-sync - Looks great, but I'd need to copy some of their code into this code base and I don't actually understand what the code is doing which means I would not be able to enhance or modify it going forward.
2. https://github.com/dtcooper/python-fitparse - Only supports parsing fit files, not writing them. There is a branch where someone has added writing support but same as point 1, I don't understand it well enough to pull into this project and support long term.
3. The FIT protocol is very complex and the C# library I'm using is easy to use and officially published by Garmin itself.
4. In the age of .netcore, this project should continue to run on multiple OS's.
5. My day job is C#, I only dabble in python on the weekends.

**Comment by philosowaffle** [comment]
Sample power zone data from matt: https://members.onepeloton.com/members/69d10cf583dc4832a1fd8512410fe013/workouts/9e53af0106c04734bbc12380742d6f3c

**Pull request closed without merging**
