### PR TITLE
fix(#534): Explicitly define default value for saveLocalCopy

### LINKED ISSUE #534: Sync workflow fails due to omitted false variable in config json
Running sync workflow causes causes an invalid config json file if you don't explicitly set save Local to true, as it omits the variable false.  

Started after the merge of: https://github.com/philosowaffle/peloton-to-garmin/pull/532

This error happened to me when running via GH Actions

```
 },
    "Format": {
      "Fit": true,
      "Json": false,
      "Tcx": false,
      "SaveLocalCopy": ,
      "IncludeTimeInHRZones": false,
      "IncludeTimeInPowerZones": false,
      "DeviceInfoPath": "./deviceInfo.xml"
    },
    "Peloton": {
```

Additionally, once setting to true, the output fails to save with a path character error:
```
Artifact path is not valid: /c46871a40e964879bf32d9c7055d7786_Extra_10:_Low_Impact_Ride_with_Matt_Wilpers.fit. Contains the following character: Colon : Invalid characters include: Double quote 
``` 
Haven't had a chance to look into it further yet, but noting here incase anyone happens to run into it or has immediate ideas.

### PR DESCRIPTION
**Pull request by anlesk**
When GH Action is triggered by cron - it does not respect input's default settings.

fixes #534

### CODE REVIEW

**Review by philosowaffle — APPROVED** [review]

**Comment by philosowaffle** [comment]
@anlesk any more tweaks to this coming or good to merge?

**Comment by anlesk** [comment]
@philosowaffle sorry, it is not ready yet. I was trying to fix both issues in a single hit, but because GH action runs on docker image that does not have zip installed - the latest addition of pre-zip is failing.
I'll either split in into multiple PRs or fix it within next couple of minutes ;)

**Comment by philosowaffle** [comment]
I've used this [action for zip](https://github.com/philosowaffle/peloton-to-garmin/blob/master/.github/workflows/release.yml#L152) on other workflows, should work here I believe.

**Comment by anlesk** [comment]
> I've used this [action for zip](https://github.com/philosowaffle/peloton-to-garmin/blob/master/.github/workflows/release.yml#L152) on other workflows, should work here I believe.

Interesting.. At some point, it does not seem to be working as well (https://github.com/anlesk/peloton-to-garmin/actions/runs/6364291199/job/17280467282):

`Run vimtor/action-zip@v1
  with:
    files: /app/output/fit
    dest: output.zip
    recursive: true
  env:
    OUTPUT_DIR: /app/output

----> 
Ready to zip "/app/output/fit" into output.zip
  - /app/output/fit (Not Found)

Zipped file output.zip successfully`
With output.zip being an empty archive file, even though `ls -la /app/output/fit` clearly shows files in there.

**Comment by anlesk** [comment]
@philosowaffle reverted zip operation back, as it will take more time to fix -- will file new PR.

**Comment by philosowaffle** [comment]
Really odd it doesn't seem to have the same directory context. I guess could always try running `apt-get install zip` to manually install

**Comment by anlesk** [comment]
> Really odd it doesn't seem to have the same directory context. I guess could always try running `apt-get install zip` to manually install

Yeah, that does the trick:
https://github.com/anlesk/peloton-to-garmin/actions/runs/6364383784/workflow#L99
https://github.com/anlesk/peloton-to-garmin/actions/runs/6364383784

**Pull request merged**
